version: "3"
services:
  web:
    image: plataforma5/lumartex-project:production0.2
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 300M
      restart_policy:
        condition: on-failure
    ports:
      - "5000:5000"