version: "3"
services:
  web:
    image: adolfoecs/lumartex-web:1.0.8
    environment:
    - API_URL=http://terraform-asg-example-1060644098.us-east-1.elb.amazonaws.com:8080
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 300M
      restart_policy:
        condition: on-failure
    ports:
      - "5000:5000"